# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.SiteUser')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide.Repo')),
            ],
        ),
        migrations.CreateModel(
            name='FileState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('owner_comment', models.TextField(null=True)),
                ('other_user_comment', models.TextField(null=True)),
                ('update_on', models.DateTimeField()),
                ('file_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FileEntity')),
            ],
        ),
    ]
