# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171027_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentity',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ide.Repo'),
        ),
        migrations.AlterField(
            model_name='filestate',
            name='file_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.FileEntity'),
        ),
    ]
