# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171117_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentity',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
