# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionchannel',
            name='members',
            field=models.ManyToManyField(to='ide.SiteUser'),
        ),
        migrations.AlterField(
            model_name='discussionchannel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='ide.Project'),
        ),
    ]
