# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_auto_20171026_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ide.Repo'),
        ),
    ]
