# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0004_auto_20171027_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='ide.Project'),
        ),
    ]
